version: '3.8'
services:
  main-service:
    build: main-service
    image: main_service
    container_name: main_service
    depends_on:
      - main-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=vivat
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - STATS_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:14-alpine
    container_name: main_db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=vivat
      - POSTGRES_PASSWORD=iamroot

  stats-server:
    build: stats-service/server
    image: stats_server
    container_name: stats_server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstats?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=vivat
      - SPRING_DATASOURCE_PASSWORD=iamroot
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=vivat
      - POSTGRES_PASSWORD=iamroot
